# ================================================  基础  =========================================================
FROM pytorch/pytorch:2.9.1-cuda12.6-cudnn9-runtime

# 设置环境变量
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV PATH="/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
# 设置 Hugging Face 镜像加速
# ENV HF_HOME=/root/.cache/huggingface
# ENV HF_HUB_ENABLE_HF_TRANSFER=1
ENV HF_ENDPOINT=https://hf-mirror.com

# # 设置pip源
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# 安装Python和基本工具
RUN apt-get update && apt-get install -y \
    git \
    ffmpeg \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 升级pip工具
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# # 安装特定版本的PyTorch
# RUN pip3 install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

# ================================================  工作  =========================================================
RUN mkdir -p /workspace && git clone https://gitee.com/jasonchen955/SeedVoiceConversion.git /workspace/SeedVoiceConversion
RUN pip install --no-cache-dir -r /workspace/SeedVoiceConversion/docker/requirements.txt

# 切换到API目录
WORKDIR /workspace/SeedVoiceConversion/api

# 设置启动命令
CMD ["python3", "./api.py", "--host", "0.0.0.0", "--port", "5656"]